# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cliente', '0001_initial'),
        ('Producto', '0001_initial'),
        ('Sede', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='compras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.PositiveIntegerField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('id_cliente', models.ForeignKey(blank=True, db_column='id_cliente', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cliente.clientes')),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Producto.productos')),
                ('id_sede', models.ForeignKey(blank=True, db_column='id_sede', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sede.sedes')),
            ],
            options={
                'db_table': 'compras',
            },
        ),
    ]
